arborist:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: '2026.05'
audit:
  enabled: true
  externalSecrets:
    auditG3auto: skfqa-audit-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/audit-service
    tag: '2026.05'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::222487244010:role/skfqa--skfqa-helm--audit-sqs-receiver
manifestservice:
  enabled: false
wts:
  enabled: false
awshelper:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/awshelper
    tag: '2026.05'
dashboard:
  dashboardConfig:
    bucket: dashboard-222487244010-skfqa-gen3
    prefix: gen3staging.kidsfirstdrc.org
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/gen3-statics
    tag: '2026.05'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::222487244010:role/skfqa--skfqa-helm--dashboard-access
fence:
  usersync:
    usersync: true
    userYamlS3Path: s3://kf-gen3-user/nonprd/user-nonprd.yaml
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    createK8sGoogleAppSecrets: true
    fenceConfig: skfqa-fence-config
    fenceJwtKeys: skfqa-fence-jwt
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/fence
    tag: '2026.05'
fluentd:
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    tag: v1.15.3-debian-cloudwatch-1.0
global:
  pdb: true
  aws:
    account: '222487244010'
    awsEsProxyRole: skfqa--skfqa-helm--es-access
    enabled: true
    hatchery_role: skfqa--skfqa-helm--hatchery-sa
    secretStoreServiceAccount:
      enabled: true
      roleArn: arn:aws:iam::222487244010:role/skfqa-external-secrets-sa
  dev: false
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/kf-dictionary/develop/schema.json
  environment: skfqa
  externalSecrets:
    deploy: true
  hostname: gen3staging.kidsfirstdrc.org
  fenceURL: https://gen3staging.kidsfirstdrc.org/user
  manifestGlobalExtraValues:
    kube_bucket: kube-skfqa-gen3
    logs_bucket: logs-skfqa-gen3
  maintenanceMode: 'off'
  portalApp: gitops
  postgres:
    dbCreate: false
  revproxyArn: arn:aws:acm:us-east-1:222487244010:certificate/d91de077-c452-4172-9f1e-c88c99feb9f0
  topologySpread:
    enabled: true
    topologyKey: topology.kubernetes.io/zone
    maxSkew: 1
indexd:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    serviceCreds: skfqa-indexd-service-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: '2026.05'
metadata:
  enabled: true
  esEndpoint: http://elasticsearch:9200
  externalSecrets:
    metadataG3auto: skfqa-metadata-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: '2026.05'
mutatingWebhook:
  enabled: true
peregrine:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: '2026.05'
revproxy:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: '2026.05'
  ingress:
    aws:
      group: skfqa-helm
sheepdog:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: '2026.05'
