---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-job-admin-binding
  namespace: argo-events
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: Role
  name: job-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-admin-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: karpenter-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-view-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-events
roleRef:
  kind: ClusterRole
  name: argo-argo-workflows-view
  apiGroup: rbac.authorization.k8s.io
