apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gen3-qa-brh
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm/gen3
      repoURL: https://github.com/uc-cdis/gen3-helm
      targetRevision: chore/argocd-degraded
      helm:
        releaseName: gen3-qa-brh
        valueFiles:
          - $values/devplanetv2/qa-brh.planx-pla.net/values/values.yaml
    - repoURL: 'https://github.com/uc-cdis/gen3-gitops.git'
      targetRevision: chore/qa-mickey-helm-migration
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: qa-brh-helm
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        role: gen3
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
